In [2]:
import tensorflow as tf

x = tf.constant([5, 4, 6])
y = tf.constant([5])
print(tf.math.less(x, y))

x = tf.constant([5, 4, 6])
y = tf.constant([5, 6, 7])
print(tf.math.less(x, y))

tf.Tensor([False  True False], shape=(3,), dtype=bool)
tf.Tensor([False  True  True], shape=(3,), dtype=bool)


In [3]:
import tensorflow as tf

v = tf.Variable(1.)
v.assign(2.)
v.assign_add(0.5)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.5>


In [4]:
import tensorflow as tf

w = tf.Variable([[1.], [2.]])
x = tf.constant([[3., 4.]])
v = tf.matmul(w, x)
print(v)

tf.Tensor(
[[3. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)


In [5]:
import tensorflow as tf

with tf.GradientTape(persistent=True) as tape:
    trainable = tf.Variable(1.)
    non_trainable = tf.Variable(2., trainable=False)
    x1 = trainable * 2.
    x2 = non_trainable * 3.
tape.gradient(x1, trainable)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [6]:
import tensorflow as tf

m = tf.Module()
m.v = tf.Variable([1.])
m.trainable_variables

(<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>,)

In [9]:
import tensorflow as tf
weight = tf.random.uniform([5])
x_weight = tf.reshape(weight, [5, 1, 1, 1])
y_weight = tf.reshape(weight, [5, 1])
print(x_weight, y_weight)

tf.Tensor(
[[[[0.46542895]]]


 [[[0.23678267]]]


 [[[0.69637764]]]


 [[[0.07191479]]]


 [[[0.00199592]]]], shape=(5, 1, 1, 1), dtype=float32) tf.Tensor(
[[0.46542895]
 [0.23678267]
 [0.69637764]
 [0.07191479]
 [0.00199592]], shape=(5, 1), dtype=float32)
